export const casualTshirts = [
    {
        name: 'CF-INSP-TS01-01',
        alt: 'Round Neck Camouflage Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS01-02', 'CF-INSP-TS01-03'],
    },
    {
        name: 'CF-INSP-TS02-01',
        alt: 'Round Neck Camouflage Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS02-02', 'CF-INSP-TS02-03'],
    },
    {
        name: 'CF-INSP-TS03-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS03-03', 'CF-INSP-TS03-02'],
    },
    {
        name: 'CF-INSP-TS04-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS04-03', 'CF-INSP-TS04-02'],
    },
    {
        name: 'CF-INSP-TS05-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS05-03', 'CF-INSP-TS05-02'],
    },
    {
        name: 'CF-INSP-TS06-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS06-03', 'CF-INSP-TS06-02'],
    },
    {
        name: 'CF-INSP-TS07-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS07-03', 'CF-INSP-TS07-02'],
    },
    {
        name: 'CF-INSP-TS08-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS08-03', 'CF-INSP-TS08-02'],
    },
    {
        name: 'CF-INSP-TS09-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS09-03', 'CF-INSP-TS09-02'],
    },
    {
        name: 'CF-INSP-TS10-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS10-02', 'CF-INSP-TS10-03'],
    },
    {
        name: 'CF-INSP-TS11-01',
        alt: 'Round Neck Dip Dye Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS11-02', 'CF-INSP-TS11-01'],
    },
    {
        name: 'CF-INSP-TS12-01',
        alt: 'Round Neck Camouflage Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-TS12-02', 'CF-INSP-TS12-01'],
    },

    {
        name: 'CF-REG-TS01-01',
        alt: 'Polo Tshirt White ',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS01-02', 'CF-REG-TS01-01'],
    },
    {
        name: 'CF-REG-TS02-01',
        alt: 'Polo Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS02-01', 'CF-REG-TS01-01'],
    },
    {
        name: 'CF-REG-TS03-01',
        alt: 'Polo Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS03-02', 'CF-REG-TS03-01'],
    },
    {
        name: 'CF-REG-TS04-01',
        alt: 'Round Neck Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS04-01'],
    },
    {
        name: 'CF-REG-TS05-01',
        alt: 'Round Neck Tshirt White',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS05-02', 'CF-REG-TS05-01'],
    },
    {
        name: 'CF-REG-TS06-01',
        alt: 'Round Neck Tshirt Grey',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS06-02', 'CF-REG-TS06-01'],
    },
    {
        name: 'CF-REG-TS07-01',
        alt: 'Round Neck Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS07-02', 'CF-REG-TS07-01'],
    },
    {
        name: 'CF-REG-TS08-01',
        alt: 'Full SLeeves Round Neck Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS08-03', 'CF-REG-TS08-02'],
    },
    {
        name: 'CF-REG-TS09-01',
        alt: 'Full SLeeves Round Neck Tshirt Pista Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-REG-TS09-03', 'CF-REG-TS09-02'],
    },
];
