export const coffeeMugs = [
    {
        name: 'CF-SVNR-CM01',
        alt: 'This is the tool iam the weapon',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM01-01', 'CF-SVNR-CM01-02', 'CF-SVNR-CM01-03'],
    },
    {
        name: 'CF-SVNR-CM02',
        alt: "Sniper no need to run you'll die tired",
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM02-01', 'CF-SVNR-CM02-02', 'CF-SVNR-CM02-03'],
    },
    {
        name: 'CF-SVNR-CM03',
        alt: 'One shot one kill',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM03-01', 'CF-SVNR-CM03-02', 'CF-SVNR-CM03-03'],
    },
    {
        name: 'CF-SVNR-CM04',
        alt: 'Mostly high always humble',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM04-01', 'CF-SVNR-CM04-02', 'CF-SVNR-CM04-03'],
    },
    {
        name: 'CF-SVNR-CM05',
        alt: 'Pilots fly airplanes legends fly helicopters',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM05-01', 'CF-SVNR-CM05-02', 'CF-SVNR-CM05-03'],
    },
    {
        name: 'CF-SVNR-CM06',
        alt: 'Combat medic the louder you scream the faster we come',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM06-01', 'CF-SVNR-CM06-02', 'CF-SVNR-CM06-03'],
    },
    {
        name: 'CF-SVNR-CM07',
        alt: 'I guard the nation what is your superpower',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM07-01', 'CF-SVNR-CM07-02', 'CF-SVNR-CM07-03'],
    },
    {
        name: 'CF-SVNR-CM08',
        alt: 'Girl power in the army now',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM08-01', 'CF-SVNR-CM08-02', 'CF-SVNR-CM08-03'],
    },
    {
        name: 'CF-SVNR-CM09',
        alt: 'Combat medic',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM09-01', 'CF-SVNR-CM09-02', 'CF-SVNR-CM09-03'],
    },
    {
        name: 'CF-SVNR-CM10',
        alt: 'How a real man takes a knee',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM10-01', 'CF-SVNR-CM10-02', 'CF-SVNR-CM10-03'],
    },
    {
        name: 'CF-SVNR-CM11',
        alt: 'Helicopter',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM11-01', 'CF-SVNR-CM11-02', 'CF-SVNR-CM11-03'],
    },
    {
        name: 'CF-SVNR-CM12',
        alt: 'Who dares win',
        price: '500',
        size: 'regular',
        extraImages: ['CF-SVNR-CM012-01', 'CF-SVNR-CM12-02', 'CF-SVNR-CM12-03'],
    },
];
