export const posters = [
    {
        name: 'CF-SVNR-PR01',
        alt: 'I Hold on Even when Nothing Left in me',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR01-01'],
    },
    {
        name: 'CF-SVNR-PR02',
        alt: 'Nothing Personal I Just do What I am Supposed to',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR02-01', 'CF-SVNR-PR02'],
    },
    {
        name: 'CF-SVNR-PR03',
        alt: 'Let Each Minute be Filled with Worth 60 Seconds Run, Make it Count',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR03-01', 'CF-SVNR-PR03'],
    },
    {
        name: 'CF-SVNR-PR04',
        alt: 'No Twists No Twirls, I Just Like It Straight',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR04-01', 'CF-SVNR-PR04'],
    },
    {
        name: 'CF-SVNR-PR05',
        alt: "Yours is the Earth & Everything that's in it, Believe it Achieve it",
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR05-01', 'CF-SVNR-PR05'],
    },
    {
        name: 'CF-SVNR-PR06',
        alt: 'I Too Feel the Fear, But I Do it Anyway',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR06', 'CF-SVNR-PR06-01'],
    },
    {
        name: 'CF-SVNR-PR07',
        alt: 'Odds Bite the Dust with My Bravado On and On I Go',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR07', 'CF-SVNR-PR07-01'],
    },
    {
        name: 'CF-SVNR-PR08',
        alt: 'Harder I Work Luckier I Get',
        price: '500',
        size: '13x19 Inches',
        extraImages: ['CF-SVNR-PR08', 'CF-SVNR-PR08-01'],
    },
];
