export const sweatShirts = [
    {
        name: 'CF-INSP-SS01-01',
        alt: 'Round Neck Sweatshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS01-01', 'CF-INSP-SS01-02'],
    },
    {
        name: 'CF-INSP-SS02-01',
        alt: 'Round Neck Sweatshirt Olive Green ',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS02-01', 'CF-INSP-SS02-02'],
    },
    {
        name: 'CF-INSP-SS03-01',
        alt: 'Round Neck Sweatshirt Black ',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS03-01', 'CF-INSP-SS03-02'],
    },
    {
        name: 'CF-INSP-SS05-01',
        alt: 'Hooded Neck Sweatshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS05-01', 'CF-INSP-SS05-02'],
    },
    {
        name: 'CF-INSP-SS06-01',
        alt: 'Round Neck Sweatshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS06-01', 'CF-INSP-SS06-02'],
    },
    {
        name: 'CF-INSP-SS07-01',
        alt: 'Hooded Neck Sweatshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS07-01', 'CF-INSP-SS07-02'],
    },
    {
        name: 'CF-INSP-SS08-01',
        alt: 'Hooded Neck Sweatshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS08-01', 'CF-INSP-SS08-02'],
    },
    {
        name: 'CF-INSP-SS09-01',
        alt: 'Hooded Neck Sweatshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-INSP-SS09-01', 'CF-INSP-SS09-02'],
    },
];
