export const sweatShirts = [
    {
        name: 'CF-INSP-SS01-01',
        alt: 'Round Neck Sweatshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS02-01',
        alt: 'Round Neck Sweatshirt Olive Green ',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS03-01',
        alt: 'Round Neck Sweatshirt Black ',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS05-01',
        alt: 'Hooded Neck Sweatshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS06-01',
        alt: 'Round Neck Sweatshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS07-01',
        alt: 'Hooded Neck Sweatshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS08-01',
        alt: 'Hooded Neck Sweatshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-SS09-01',
        alt: 'Hooded Neck Sweatshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
];
