export const trousers = [
    {
        name: 'CF-TAC-CT01-01',
        alt: 'Combat Trouser Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-TAC-CT01-01', 'CF-TAC-CT01-02'],
    },
    {
        name: 'CF-TAC-CT02-01',
        alt: 'Combat Trouser Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-TAC-CT02-01', 'CF-TAC-CT02-02'],
    },
    {
        name: 'CF-TAC-CT03-01',
        alt: 'Combat Trouser Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-TAC-CT03-01', 'CF-TAC-CT03-02'],
    },
    {
        name: 'CF-TAC-CT04-01',
        alt: 'Combat Trouser Dark Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-TAC-CT04-01', 'CF-TAC-CT04-02'],
    },
    {
        name: 'CF-TAC-CT05-01',
        alt: 'Combat Trouser Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-TAC-CT05-01', 'CF-TAC-CT05-02'],
    },
    {
        name: 'CF-TAC-CT06-01',
        alt: 'Combat Trouser Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
        extraImages: ['CF-TAC-CT06-01', 'CF-TAC-CT06-01'],
    },
];
