export const tshirts = [
    {
        name: 'CF-TAC-TS01-01',
        alt: 'Full Sleeves Tactical Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS02-01',
        alt: 'Full Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS03-01',
        alt: 'Full Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS04-01',
        alt: 'Full Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS05-01',
        alt: 'Full Sleeves Tactical Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS06-01',
        alt: 'Full Sleeves Tactical Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS07-01',
        alt: 'Half Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS08-01',
        alt: 'Half Sleeves Tactical Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS09-01',
        alt: 'Half Sleeves Round Neck Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS10-01',
        alt: 'Full Sleeves Round Neck Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
];
