export const tshirts = [
    {
        name: 'CF-TAC-TS01-01',
        alt: 'Full Sleeves Tactical Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS02-01',
        alt: 'Full Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS03-01',
        alt: 'Full Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS04-01',
        alt: 'Full Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS05-01',
        alt: 'Full Sleeves Tactical Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS06-01',
        alt: 'Full Sleeves Tactical Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS07-01',
        alt: 'Half Sleeves Tactical Tshirt Camouflage',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS08-01',
        alt: 'Half Sleeves Tactical Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS09-01',
        alt: 'Half Sleeves Round Neck Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-TAC-TS10-01',
        alt: 'Full Sleeves Round Neck Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS01-01',
        alt: 'Round Neck Camouflage Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS02-01',
        alt: 'Round Neck Camouflage Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS03-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS04-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS05-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS06-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS07-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS08-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS09-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS10-01',
        alt: 'Round Neck Printed Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS11-01',
        alt: 'Round Neck Dip Dye Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-INSP-TS12-01',
        alt: 'Round Neck Camouflage Tshirt',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },

    {
        name: 'CF-REG-TS01-01',
        alt: 'Polo Tshirt White ',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS02-01',
        alt: 'Polo Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS03-01',
        alt: 'Polo Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS04-01',
        alt: 'Round Neck Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS05-01',
        alt: 'Round Neck Tshirt White',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS06-01',
        alt: 'Round Neck Tshirt Grey',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS07-01',
        alt: 'Round Neck Tshirt Olive Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS08-01',
        alt: 'Full SLeeves Round Neck Tshirt Black',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
    {
        name: 'CF-REG-TS09-01',
        alt: 'Full SLeeves Round Neck Tshirt Pista Green',
        price: '500',
        size: 'XL',
        fit: 'regular',
    },
];
